#!/usr/bin/env python
'''
Autogenerated code using /Users/palesiak/git/cobrasdkgen/cobrasdkgen.py
Original source file: <StringIO.StringIO instance at 0x100840e60>
'''

import cobra.mit.access
import cobra.mit.session
import cobra.mit.request
import cobra.model.ctrlr
import cobra.model.fabric
from cobra.internal.codec.xmlcodec import toXMLStr
# import httplib; httplib.HTTPConnection.debuglevel = 1

def registerFabric(md):
	topMo = md.lookupByDn('uni')

	# build the request using cobra syntax
	ctrlrInst = cobra.model.ctrlr.Inst(topMo)
	fabricNodeIdentPol = cobra.model.fabric.NodeIdentPol(ctrlrInst)
	fabricNodeIdentP = cobra.model.fabric.NodeIdentP(fabricNodeIdentPol, serial='TEP-1-101', name='leaf1', nodeId='101')
	fabricNodeIdentP2 = cobra.model.fabric.NodeIdentP(fabricNodeIdentPol, serial='TEP-1-102', name='leaf2', nodeId='102')
	fabricNodeIdentP3 = cobra.model.fabric.NodeIdentP(fabricNodeIdentPol, serial='TEP-1-103', name='spine1', nodeId='103')
	fabricNodeIdentP4 = cobra.model.fabric.NodeIdentP(fabricNodeIdentPol, serial='TEP-1-104', name='spine2', nodeId='104')

	c = cobra.mit.request.ConfigRequest()
	# print toXMLStr(ctrlrInst)
	c.addMo(ctrlrInst)
	md.commit(c)


# log into an APIC and create a directory object
ep = cobra.mit.access.EndPoint('ip', secure=False, port=80)
ls = cobra.mit.session.LoginSession('admin', 'password')
md = cobra.mit.access.MoDirectory(ep, ls)
md.login()

registerFabric(md)
